# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 4.3

# The generator used is:
set(CMAKE_DEPENDS_GENERATOR "NMake Makefiles")

# The top level Makefile was generated from the following files:
set(CMAKE_MAKEFILE_DEPENDS
  "CMakeCache.txt"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeCXXInformation.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeCommonLanguageInclude.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeFindDependencyMacro.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeGenericSystem.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeInitializeConfigs.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeLanguageInformation.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeRCInformation.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeSystemSpecificInformation.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeSystemSpecificInitialize.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/CTest.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/CTestTargets.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/CTestUseLaunchers.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/Compiler/CMakeCommonCompilerMacros.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/Compiler/MSVC-CXX.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/Compiler/MSVC.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/DartConfiguration.tcl.in"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/Internal/CMakeCXXLinkerInformation.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/Internal/CMakeCommonLinkerInformation.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/Linker/MSVC-CXX.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/Linker/MSVC.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/Platform/Linker/Windows-MSVC-CXX.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/Platform/Linker/Windows-MSVC.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/Platform/Windows-Initialize.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/Platform/Windows-MSVC-CXX.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/Platform/Windows-MSVC.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/Platform/Windows.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Modules/Platform/WindowsPaths.cmake"
  "C:/Program Files/CMake/share/cmake-4.3/Templates/CTestScript.cmake.in"
  "C:/Users/mrwge/Documents/anti gravity/claude/osgui/build-verify-release/install/lib/cmake/OSGui/OSGuiConfig.cmake"
  "C:/Users/mrwge/Documents/anti gravity/claude/osgui/build-verify-release/install/lib/cmake/OSGui/OSGuiConfigVersion.cmake"
  "C:/Users/mrwge/Documents/anti gravity/claude/osgui/build-verify-release/install/lib/cmake/OSGui/OSGuiTargets-release.cmake"
  "C:/Users/mrwge/Documents/anti gravity/claude/osgui/build-verify-release/install/lib/cmake/OSGui/OSGuiTargets.cmake"
  "C:/Users/mrwge/Documents/anti gravity/claude/osgui/cmake/package-consumer/CMakeLists.txt"
  "CMakeFiles/4.3.3/CMakeCXXCompiler.cmake"
  "CMakeFiles/4.3.3/CMakeRCCompiler.cmake"
  "CMakeFiles/4.3.3/CMakeSystem.cmake"
  )

# The corresponding makefile is:
set(CMAKE_MAKEFILE_OUTPUTS
  "Makefile"
  "CMakeFiles/cmake.check_cache"
  )

# Byproducts of CMake generate step:
set(CMAKE_MAKEFILE_PRODUCTS
  "DartConfiguration.tcl"
  "CMakeFiles/CTestScript.cmake"
  "CMakeFiles/CMakeDirectoryInformation.cmake"
  )

# Dependency information for all targets:
set(CMAKE_DEPEND_INFO_FILES
  "CMakeFiles/Experimental.dir/DependInfo.cmake"
  "CMakeFiles/Nightly.dir/DependInfo.cmake"
  "CMakeFiles/Continuous.dir/DependInfo.cmake"
  "CMakeFiles/NightlyMemoryCheck.dir/DependInfo.cmake"
  "CMakeFiles/NightlyStart.dir/DependInfo.cmake"
  "CMakeFiles/NightlyUpdate.dir/DependInfo.cmake"
  "CMakeFiles/NightlyConfigure.dir/DependInfo.cmake"
  "CMakeFiles/NightlyBuild.dir/DependInfo.cmake"
  "CMakeFiles/NightlyTest.dir/DependInfo.cmake"
  "CMakeFiles/NightlyCoverage.dir/DependInfo.cmake"
  "CMakeFiles/NightlyMemCheck.dir/DependInfo.cmake"
  "CMakeFiles/NightlySubmit.dir/DependInfo.cmake"
  "CMakeFiles/ExperimentalStart.dir/DependInfo.cmake"
  "CMakeFiles/ExperimentalUpdate.dir/DependInfo.cmake"
  "CMakeFiles/ExperimentalConfigure.dir/DependInfo.cmake"
  "CMakeFiles/ExperimentalBuild.dir/DependInfo.cmake"
  "CMakeFiles/ExperimentalTest.dir/DependInfo.cmake"
  "CMakeFiles/ExperimentalCoverage.dir/DependInfo.cmake"
  "CMakeFiles/ExperimentalMemCheck.dir/DependInfo.cmake"
  "CMakeFiles/ExperimentalSubmit.dir/DependInfo.cmake"
  "CMakeFiles/ContinuousStart.dir/DependInfo.cmake"
  "CMakeFiles/ContinuousUpdate.dir/DependInfo.cmake"
  "CMakeFiles/ContinuousConfigure.dir/DependInfo.cmake"
  "CMakeFiles/ContinuousBuild.dir/DependInfo.cmake"
  "CMakeFiles/ContinuousTest.dir/DependInfo.cmake"
  "CMakeFiles/ContinuousCoverage.dir/DependInfo.cmake"
  "CMakeFiles/ContinuousMemCheck.dir/DependInfo.cmake"
  "CMakeFiles/ContinuousSubmit.dir/DependInfo.cmake"
  "CMakeFiles/osgui_package_consumer.dir/DependInfo.cmake"
  )
