# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\mrwge\Documents\anti gravity\claude\osgui"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	echo >nul && "C:\Program Files\CMake\bin\ctest.exe" $(ARGS)
.PHONY : test

# Special rule for the target test
test\fast: test
.PHONY : test\fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	echo >nul && "C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache
.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	echo >nul && "C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache
.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build\CMakeFiles" "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean
.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named osgui

# Build rule for target.
osgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) osgui
.PHONY : osgui

# fast build rule for target.
osgui\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui.dir\build
.PHONY : osgui\fast

#=============================================================================
# Target rules for targets named osgui_examples

# Build rule for target.
osgui_examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) osgui_examples
.PHONY : osgui_examples

# fast build rule for target.
osgui_examples\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_examples.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_examples.dir\build
.PHONY : osgui_examples\fast

#=============================================================================
# Target rules for targets named osgui_opengl3

# Build rule for target.
osgui_opengl3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) osgui_opengl3
.PHONY : osgui_opengl3

# fast build rule for target.
osgui_opengl3\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_opengl3.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_opengl3.dir\build
.PHONY : osgui_opengl3\fast

#=============================================================================
# Target rules for targets named osgui_win32_opengl2

# Build rule for target.
osgui_win32_opengl2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) osgui_win32_opengl2
.PHONY : osgui_win32_opengl2

# fast build rule for target.
osgui_win32_opengl2\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_win32_opengl2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_win32_opengl2.dir\build
.PHONY : osgui_win32_opengl2\fast

#=============================================================================
# Target rules for targets named osgui_dx11

# Build rule for target.
osgui_dx11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) osgui_dx11
.PHONY : osgui_dx11

# fast build rule for target.
osgui_dx11\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_dx11.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_dx11.dir\build
.PHONY : osgui_dx11\fast

#=============================================================================
# Target rules for targets named osgui_demo

# Build rule for target.
osgui_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) osgui_demo
.PHONY : osgui_demo

# fast build rule for target.
osgui_demo\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_demo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_demo.dir\build
.PHONY : osgui_demo\fast

#=============================================================================
# Target rules for targets named osgui_tests

# Build rule for target.
osgui_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) osgui_tests
.PHONY : osgui_tests

# fast build rule for target.
osgui_tests\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_tests.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_tests.dir\build
.PHONY : osgui_tests\fast

examples\osgui_examples.obj: examples\osgui_examples.cpp.obj
.PHONY : examples\osgui_examples.obj

# target to build an object file
examples\osgui_examples.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_examples.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_examples.dir\examples\osgui_examples.cpp.obj
.PHONY : examples\osgui_examples.cpp.obj

examples\osgui_examples.i: examples\osgui_examples.cpp.i
.PHONY : examples\osgui_examples.i

# target to preprocess a source file
examples\osgui_examples.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_examples.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_examples.dir\examples\osgui_examples.cpp.i
.PHONY : examples\osgui_examples.cpp.i

examples\osgui_examples.s: examples\osgui_examples.cpp.s
.PHONY : examples\osgui_examples.s

# target to generate assembly for a file
examples\osgui_examples.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_examples.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_examples.dir\examples\osgui_examples.cpp.s
.PHONY : examples\osgui_examples.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_demo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_demo.dir\main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_demo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_demo.dir\main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_demo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_demo.dir\main.cpp.s
.PHONY : main.cpp.s

osgui.obj: osgui.cpp.obj
.PHONY : osgui.obj

# target to build an object file
osgui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui.dir\osgui.cpp.obj
.PHONY : osgui.cpp.obj

osgui.i: osgui.cpp.i
.PHONY : osgui.i

# target to preprocess a source file
osgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui.dir\osgui.cpp.i
.PHONY : osgui.cpp.i

osgui.s: osgui.cpp.s
.PHONY : osgui.s

# target to generate assembly for a file
osgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui.dir\osgui.cpp.s
.PHONY : osgui.cpp.s

osgui_demo.obj: osgui_demo.cpp.obj
.PHONY : osgui_demo.obj

# target to build an object file
osgui_demo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_demo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_demo.dir\osgui_demo.cpp.obj
.PHONY : osgui_demo.cpp.obj

osgui_demo.i: osgui_demo.cpp.i
.PHONY : osgui_demo.i

# target to preprocess a source file
osgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_demo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_demo.dir\osgui_demo.cpp.i
.PHONY : osgui_demo.cpp.i

osgui_demo.s: osgui_demo.cpp.s
.PHONY : osgui_demo.s

# target to generate assembly for a file
osgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_demo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_demo.dir\osgui_demo.cpp.s
.PHONY : osgui_demo.cpp.s

osgui_impl_dx11.obj: osgui_impl_dx11.cpp.obj
.PHONY : osgui_impl_dx11.obj

# target to build an object file
osgui_impl_dx11.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_dx11.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_dx11.dir\osgui_impl_dx11.cpp.obj
.PHONY : osgui_impl_dx11.cpp.obj

osgui_impl_dx11.i: osgui_impl_dx11.cpp.i
.PHONY : osgui_impl_dx11.i

# target to preprocess a source file
osgui_impl_dx11.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_dx11.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_dx11.dir\osgui_impl_dx11.cpp.i
.PHONY : osgui_impl_dx11.cpp.i

osgui_impl_dx11.s: osgui_impl_dx11.cpp.s
.PHONY : osgui_impl_dx11.s

# target to generate assembly for a file
osgui_impl_dx11.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_dx11.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_dx11.dir\osgui_impl_dx11.cpp.s
.PHONY : osgui_impl_dx11.cpp.s

osgui_impl_opengl2.obj: osgui_impl_opengl2.cpp.obj
.PHONY : osgui_impl_opengl2.obj

# target to build an object file
osgui_impl_opengl2.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_win32_opengl2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_win32_opengl2.dir\osgui_impl_opengl2.cpp.obj
.PHONY : osgui_impl_opengl2.cpp.obj

osgui_impl_opengl2.i: osgui_impl_opengl2.cpp.i
.PHONY : osgui_impl_opengl2.i

# target to preprocess a source file
osgui_impl_opengl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_win32_opengl2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_win32_opengl2.dir\osgui_impl_opengl2.cpp.i
.PHONY : osgui_impl_opengl2.cpp.i

osgui_impl_opengl2.s: osgui_impl_opengl2.cpp.s
.PHONY : osgui_impl_opengl2.s

# target to generate assembly for a file
osgui_impl_opengl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_win32_opengl2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_win32_opengl2.dir\osgui_impl_opengl2.cpp.s
.PHONY : osgui_impl_opengl2.cpp.s

osgui_impl_opengl3.obj: osgui_impl_opengl3.cpp.obj
.PHONY : osgui_impl_opengl3.obj

# target to build an object file
osgui_impl_opengl3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_opengl3.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_opengl3.dir\osgui_impl_opengl3.cpp.obj
.PHONY : osgui_impl_opengl3.cpp.obj

osgui_impl_opengl3.i: osgui_impl_opengl3.cpp.i
.PHONY : osgui_impl_opengl3.i

# target to preprocess a source file
osgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_opengl3.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_opengl3.dir\osgui_impl_opengl3.cpp.i
.PHONY : osgui_impl_opengl3.cpp.i

osgui_impl_opengl3.s: osgui_impl_opengl3.cpp.s
.PHONY : osgui_impl_opengl3.s

# target to generate assembly for a file
osgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_opengl3.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_opengl3.dir\osgui_impl_opengl3.cpp.s
.PHONY : osgui_impl_opengl3.cpp.s

osgui_impl_win32.obj: osgui_impl_win32.cpp.obj
.PHONY : osgui_impl_win32.obj

# target to build an object file
osgui_impl_win32.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_win32_opengl2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_win32_opengl2.dir\osgui_impl_win32.cpp.obj
.PHONY : osgui_impl_win32.cpp.obj

osgui_impl_win32.i: osgui_impl_win32.cpp.i
.PHONY : osgui_impl_win32.i

# target to preprocess a source file
osgui_impl_win32.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_win32_opengl2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_win32_opengl2.dir\osgui_impl_win32.cpp.i
.PHONY : osgui_impl_win32.cpp.i

osgui_impl_win32.s: osgui_impl_win32.cpp.s
.PHONY : osgui_impl_win32.s

# target to generate assembly for a file
osgui_impl_win32.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_win32_opengl2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_win32_opengl2.dir\osgui_impl_win32.cpp.s
.PHONY : osgui_impl_win32.cpp.s

osgui_theme_editor.obj: osgui_theme_editor.cpp.obj
.PHONY : osgui_theme_editor.obj

# target to build an object file
osgui_theme_editor.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_demo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_demo.dir\osgui_theme_editor.cpp.obj
.PHONY : osgui_theme_editor.cpp.obj

osgui_theme_editor.i: osgui_theme_editor.cpp.i
.PHONY : osgui_theme_editor.i

# target to preprocess a source file
osgui_theme_editor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_demo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_demo.dir\osgui_theme_editor.cpp.i
.PHONY : osgui_theme_editor.cpp.i

osgui_theme_editor.s: osgui_theme_editor.cpp.s
.PHONY : osgui_theme_editor.s

# target to generate assembly for a file
osgui_theme_editor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_demo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_demo.dir\osgui_theme_editor.cpp.s
.PHONY : osgui_theme_editor.cpp.s

tests\osgui_tests.obj: tests\osgui_tests.cpp.obj
.PHONY : tests\osgui_tests.obj

# target to build an object file
tests\osgui_tests.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_tests.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_tests.dir\tests\osgui_tests.cpp.obj
.PHONY : tests\osgui_tests.cpp.obj

tests\osgui_tests.i: tests\osgui_tests.cpp.i
.PHONY : tests\osgui_tests.i

# target to preprocess a source file
tests\osgui_tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_tests.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_tests.dir\tests\osgui_tests.cpp.i
.PHONY : tests\osgui_tests.cpp.i

tests\osgui_tests.s: tests\osgui_tests.cpp.s
.PHONY : tests\osgui_tests.s

# target to generate assembly for a file
tests\osgui_tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\osgui_tests.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\osgui_tests.dir\tests\osgui_tests.cpp.s
.PHONY : tests\osgui_tests.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... test
	@echo ... osgui
	@echo ... osgui_demo
	@echo ... osgui_dx11
	@echo ... osgui_examples
	@echo ... osgui_opengl3
	@echo ... osgui_tests
	@echo ... osgui_win32_opengl2
	@echo ... examples/osgui_examples.obj
	@echo ... examples/osgui_examples.i
	@echo ... examples/osgui_examples.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... osgui.obj
	@echo ... osgui.i
	@echo ... osgui.s
	@echo ... osgui_demo.obj
	@echo ... osgui_demo.i
	@echo ... osgui_demo.s
	@echo ... osgui_impl_dx11.obj
	@echo ... osgui_impl_dx11.i
	@echo ... osgui_impl_dx11.s
	@echo ... osgui_impl_opengl2.obj
	@echo ... osgui_impl_opengl2.i
	@echo ... osgui_impl_opengl2.s
	@echo ... osgui_impl_opengl3.obj
	@echo ... osgui_impl_opengl3.i
	@echo ... osgui_impl_opengl3.s
	@echo ... osgui_impl_win32.obj
	@echo ... osgui_impl_win32.i
	@echo ... osgui_impl_win32.s
	@echo ... osgui_theme_editor.obj
	@echo ... osgui_theme_editor.i
	@echo ... osgui_theme_editor.s
	@echo ... tests/osgui_tests.obj
	@echo ... tests/osgui_tests.i
	@echo ... tests/osgui_tests.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

