#include "osgui_impl_glfw.h"
#include <GLFW/glfw3.h>
#include <stdlib.h>

static GLFWwindow* g_Window=0;static double g_Time=0;static OG_GlfwFontBuilder g_FontBuilder=0;static void* g_FontUser=0;static float g_Dpi=1;
static GLFWkeyfun g_PrevKey=0;static GLFWcharfun g_PrevChar=0;static GLFWscrollfun g_PrevScroll=0;

static int MapKey(int key){if(key>=GLFW_KEY_A&&key<=GLFW_KEY_Z)return 'A'+key-GLFW_KEY_A;if(key>=GLFW_KEY_0&&key<=GLFW_KEY_9)return '0'+key-GLFW_KEY_0;switch(key){case GLFW_KEY_TAB:return 9;case GLFW_KEY_ENTER:return 13;case GLFW_KEY_ESCAPE:return 27;case GLFW_KEY_SPACE:return 32;case GLFW_KEY_BACKSPACE:return 8;case GLFW_KEY_DELETE:return 46;case GLFW_KEY_LEFT:return 37;case GLFW_KEY_UP:return 38;case GLFW_KEY_RIGHT:return 39;case GLFW_KEY_DOWN:return 40;case GLFW_KEY_HOME:return 36;case GLFW_KEY_END:return 35;case GLFW_KEY_LEFT_SHIFT:case GLFW_KEY_RIGHT_SHIFT:return 16;case GLFW_KEY_LEFT_CONTROL:case GLFW_KEY_RIGHT_CONTROL:return 17;default:return -1;}}
static void KeyCallback(GLFWwindow* w,int key,int scancode,int action,int mods){int mapped=MapKey(key);if(mapped>=0)og::GetIO().key_down[mapped]=action!=GLFW_RELEASE;if(g_PrevKey)g_PrevKey(w,key,scancode,action,mods);}
static void CharCallback(GLFWwindow* w,unsigned int cp){og::IO& io=og::GetIO();if(io.input_char_count<32)io.input_chars[io.input_char_count++]=cp;if(g_PrevChar)g_PrevChar(w,cp);}
static void ScrollCallback(GLFWwindow* w,double x,double y){(void)x;og::GetIO().mouse_wheel+=(float)y;if(g_PrevScroll)g_PrevScroll(w,x,y);}
static const char* GetClipboard(void*){const char* text=glfwGetClipboardString(g_Window);return text?text:"";}
static void SetClipboard(void*,const char* text){glfwSetClipboardString(g_Window,text?text:"");}
void OG_ImplGlfw_SetFontBuilder(OG_GlfwFontBuilder builder,void* user){g_FontBuilder=builder;g_FontUser=user;}
bool OG_ImplGlfw_Init(GLFWwindow* window,bool install){if(!window)return false;g_Window=window;g_Time=glfwGetTime();og::IO& io=og::GetIO();io.get_clipboard_text=GetClipboard;io.set_clipboard_text=SetClipboard;if(install){g_PrevKey=glfwSetKeyCallback(window,KeyCallback);g_PrevChar=glfwSetCharCallback(window,CharCallback);g_PrevScroll=glfwSetScrollCallback(window,ScrollCallback);}return true;}
void OG_ImplGlfw_Shutdown(){if(g_Window){if(g_PrevKey)glfwSetKeyCallback(g_Window,g_PrevKey);if(g_PrevChar)glfwSetCharCallback(g_Window,g_PrevChar);if(g_PrevScroll)glfwSetScrollCallback(g_Window,g_PrevScroll);}g_Window=0;g_PrevKey=0;g_PrevChar=0;g_PrevScroll=0;}
void OG_ImplGlfw_NewFrame(){if(!g_Window)return;og::IO& io=og::GetIO();int width=0,height=0,fbw=0,fbh=0;glfwGetWindowSize(g_Window,&width,&height);glfwGetFramebufferSize(g_Window,&fbw,&fbh);io.display_size=og::Vec2((float)width,(float)height);io.framebuffer_scale=og::Vec2(width>0?(float)fbw/width:1,height>0?(float)fbh/height:1);float xs=1,ys=1;glfwGetWindowContentScale(g_Window,&xs,&ys);float dpi=xs>0?xs:1;if(dpi!=g_Dpi||!og::GetFontAtlas().pixels){g_Dpi=dpi;io.dpi_scale=dpi;og::SetUIScale(dpi);if(g_FontBuilder){if(og::GetFontAtlas().pixels){free(og::GetFontAtlas().pixels);og::GetFontAtlas().pixels=0;}g_FontBuilder(og::GetFontAtlas(),dpi,g_FontUser);og::GetFontAtlas().tex_id=0;}}double now=glfwGetTime();io.delta_time=g_Time>0?(float)(now-g_Time):1.0f/60.0f;g_Time=now;double mx=0,my=0;glfwGetCursorPos(g_Window,&mx,&my);io.mouse_pos=og::Vec2((float)mx,(float)my);io.mouse_down[0]=glfwGetMouseButton(g_Window,GLFW_MOUSE_BUTTON_LEFT)==GLFW_PRESS;io.mouse_down[1]=glfwGetMouseButton(g_Window,GLFW_MOUSE_BUTTON_RIGHT)==GLFW_PRESS;io.mouse_down[2]=glfwGetMouseButton(g_Window,GLFW_MOUSE_BUTTON_MIDDLE)==GLFW_PRESS;}
