#include "osgui_impl_dx11.h"
#include <d3d11.h>
#include <d3dcompiler.h>
#include <map>
#include <string.h>
#include <vector>

#pragma comment(lib, "d3d11.lib")
#pragma comment(lib, "d3dcompiler.lib")

struct VertexConstantBuffer { float mvp[4][4]; };
static ID3D11Device* g_Device=0;static ID3D11DeviceContext* g_Context=0;
static ID3D11Buffer* g_VB=0;static ID3D11Buffer* g_IB=0;static int g_VBSize=5000,g_IBSize=10000;
static ID3D11VertexShader* g_VS=0;static ID3D11PixelShader* g_PS=0;static ID3D11InputLayout* g_Layout=0;static ID3D11Buffer* g_ConstantBuffer=0;
static ID3D11SamplerState* g_Sampler=0;static ID3D11BlendState* g_Blend=0;static ID3D11RasterizerState* g_Raster=0;static ID3D11DepthStencilState* g_Depth=0;
static ID3D11ShaderResourceView* g_FontView=0;static ID3D11Texture2D* g_FontTexture=0;static std::map<unsigned int,ID3D11ShaderResourceView*> g_Textures;static unsigned int g_NextTexture=2;

unsigned int OG_ImplDX11_RegisterTexture(ID3D11ShaderResourceView* texture){if(!texture)return 0;unsigned int id=g_NextTexture++;texture->AddRef();g_Textures[id]=texture;return id;}
void OG_ImplDX11_UnregisterTexture(unsigned int id){std::map<unsigned int,ID3D11ShaderResourceView*>::iterator it=g_Textures.find(id);if(it!=g_Textures.end()){it->second->Release();g_Textures.erase(it);}}
static ID3D11ShaderResourceView* FindTexture(unsigned int id){std::map<unsigned int,ID3D11ShaderResourceView*>::iterator it=g_Textures.find(id);return it!=g_Textures.end()?it->second:g_FontView;}

bool OG_ImplDX11_Init(ID3D11Device* device,ID3D11DeviceContext* context){if(!device||!context)return false;g_Device=device;g_Context=context;g_Device->AddRef();g_Context->AddRef();return true;}
bool OG_ImplDX11_CreateDeviceObjects(){if(!g_Device)return false;
    const char* shader="cbuffer vertexBuffer:register(b0){float4x4 ProjectionMatrix;};struct VS_IN{float2 pos:POSITION;float2 uv:TEXCOORD0;float4 col:COLOR0;};struct PS_IN{float4 pos:SV_POSITION;float2 uv:TEXCOORD0;float4 col:COLOR0;};PS_IN VSMain(VS_IN i){PS_IN o;o.pos=mul(ProjectionMatrix,float4(i.pos.xy,0,1));o.uv=i.uv;o.col=i.col;return o;}Texture2D texture0:register(t0);SamplerState sampler0:register(s0);float4 PSMain(PS_IN i):SV_Target{return i.col*texture0.Sample(sampler0,i.uv);}";
    ID3DBlob *vs=0,*ps=0,*errors=0;if(FAILED(D3DCompile(shader,strlen(shader),0,0,0,"VSMain","vs_4_0",0,0,&vs,&errors))){if(errors)errors->Release();return false;}if(FAILED(D3DCompile(shader,strlen(shader),0,0,0,"PSMain","ps_4_0",0,0,&ps,&errors))){vs->Release();if(errors)errors->Release();return false;}
    HRESULT hr=g_Device->CreateVertexShader(vs->GetBufferPointer(),vs->GetBufferSize(),0,&g_VS);if(SUCCEEDED(hr))hr=g_Device->CreatePixelShader(ps->GetBufferPointer(),ps->GetBufferSize(),0,&g_PS);
    D3D11_INPUT_ELEMENT_DESC elements[]={{"POSITION",0,DXGI_FORMAT_R32G32_FLOAT,0,(UINT)offsetof(og::DrawVert,pos),D3D11_INPUT_PER_VERTEX_DATA,0},{"TEXCOORD",0,DXGI_FORMAT_R32G32_FLOAT,0,(UINT)offsetof(og::DrawVert,uv),D3D11_INPUT_PER_VERTEX_DATA,0},{"COLOR",0,DXGI_FORMAT_R8G8B8A8_UNORM,0,(UINT)offsetof(og::DrawVert,col),D3D11_INPUT_PER_VERTEX_DATA,0}};
    if(SUCCEEDED(hr))hr=g_Device->CreateInputLayout(elements,3,vs->GetBufferPointer(),vs->GetBufferSize(),&g_Layout);vs->Release();ps->Release();if(FAILED(hr))return false;
    D3D11_BUFFER_DESC cb={};cb.ByteWidth=sizeof(VertexConstantBuffer);cb.Usage=D3D11_USAGE_DYNAMIC;cb.BindFlags=D3D11_BIND_CONSTANT_BUFFER;cb.CPUAccessFlags=D3D11_CPU_ACCESS_WRITE;if(FAILED(g_Device->CreateBuffer(&cb,0,&g_ConstantBuffer)))return false;
    D3D11_SAMPLER_DESC sd={};sd.Filter=D3D11_FILTER_MIN_MAG_MIP_LINEAR;sd.AddressU=sd.AddressV=sd.AddressW=D3D11_TEXTURE_ADDRESS_CLAMP;sd.ComparisonFunc=D3D11_COMPARISON_ALWAYS;sd.MinLOD=0;sd.MaxLOD=D3D11_FLOAT32_MAX;if(FAILED(g_Device->CreateSamplerState(&sd,&g_Sampler)))return false;
    D3D11_BLEND_DESC bd={};bd.AlphaToCoverageEnable=FALSE;bd.RenderTarget[0].BlendEnable=TRUE;bd.RenderTarget[0].SrcBlend=D3D11_BLEND_SRC_ALPHA;bd.RenderTarget[0].DestBlend=D3D11_BLEND_INV_SRC_ALPHA;bd.RenderTarget[0].BlendOp=D3D11_BLEND_OP_ADD;bd.RenderTarget[0].SrcBlendAlpha=D3D11_BLEND_ONE;bd.RenderTarget[0].DestBlendAlpha=D3D11_BLEND_INV_SRC_ALPHA;bd.RenderTarget[0].BlendOpAlpha=D3D11_BLEND_OP_ADD;bd.RenderTarget[0].RenderTargetWriteMask=D3D11_COLOR_WRITE_ENABLE_ALL;if(FAILED(g_Device->CreateBlendState(&bd,&g_Blend)))return false;
    D3D11_RASTERIZER_DESC rd={};rd.FillMode=D3D11_FILL_SOLID;rd.CullMode=D3D11_CULL_NONE;rd.ScissorEnable=TRUE;rd.DepthClipEnable=TRUE;if(FAILED(g_Device->CreateRasterizerState(&rd,&g_Raster)))return false;
    D3D11_DEPTH_STENCIL_DESC dd={};dd.DepthEnable=FALSE;dd.StencilEnable=FALSE;if(FAILED(g_Device->CreateDepthStencilState(&dd,&g_Depth)))return false;
    og::FontAtlas& a=og::GetFontAtlas();if(!a.pixels)return false;std::vector<unsigned char> rgba((size_t)a.width*a.height*4);for(int i=0;i<a.width*a.height;++i){rgba[(size_t)i*4]=rgba[(size_t)i*4+1]=rgba[(size_t)i*4+2]=255;rgba[(size_t)i*4+3]=a.pixels[i];}D3D11_TEXTURE2D_DESC td={};td.Width=a.width;td.Height=a.height;td.MipLevels=1;td.ArraySize=1;td.Format=DXGI_FORMAT_R8G8B8A8_UNORM;td.SampleDesc.Count=1;td.Usage=D3D11_USAGE_IMMUTABLE;td.BindFlags=D3D11_BIND_SHADER_RESOURCE;D3D11_SUBRESOURCE_DATA sub={rgba.data(),(UINT)a.width*4,0};if(FAILED(g_Device->CreateTexture2D(&td,&sub,&g_FontTexture)))return false;D3D11_SHADER_RESOURCE_VIEW_DESC sv={};sv.Format=td.Format;sv.ViewDimension=D3D11_SRV_DIMENSION_TEXTURE2D;sv.Texture2D.MipLevels=1;if(FAILED(g_Device->CreateShaderResourceView(g_FontTexture,&sv,&g_FontView)))return false;a.tex_id=1;g_Textures[1]=g_FontView;g_FontView->AddRef();return true;
}
void OG_ImplDX11_InvalidateDeviceObjects(){for(std::map<unsigned int,ID3D11ShaderResourceView*>::iterator it=g_Textures.begin();it!=g_Textures.end();++it)it->second->Release();g_Textures.clear();if(g_FontView){g_FontView->Release();g_FontView=0;}if(g_FontTexture){g_FontTexture->Release();g_FontTexture=0;}if(g_VB){g_VB->Release();g_VB=0;}if(g_IB){g_IB->Release();g_IB=0;}if(g_VS){g_VS->Release();g_VS=0;}if(g_PS){g_PS->Release();g_PS=0;}if(g_Layout){g_Layout->Release();g_Layout=0;}if(g_ConstantBuffer){g_ConstantBuffer->Release();g_ConstantBuffer=0;}if(g_Sampler){g_Sampler->Release();g_Sampler=0;}if(g_Blend){g_Blend->Release();g_Blend=0;}if(g_Raster){g_Raster->Release();g_Raster=0;}if(g_Depth){g_Depth->Release();g_Depth=0;}if(og::GetFontAtlas().tex_id)og::GetFontAtlas().tex_id=0;}
void OG_ImplDX11_Shutdown(){OG_ImplDX11_InvalidateDeviceObjects();if(g_Context){g_Context->Release();g_Context=0;}if(g_Device){g_Device->Release();g_Device=0;}}
void OG_ImplDX11_NewFrame(){if(!g_VS)OG_ImplDX11_CreateDeviceObjects();else if(!og::GetFontAtlas().tex_id){OG_ImplDX11_InvalidateDeviceObjects();OG_ImplDX11_CreateDeviceObjects();}}
void OG_ImplDX11_RenderDrawData(og::DrawData* data){if(!data||data->display_size.x<=0||data->display_size.y<=0)return;if(!g_VS&&!OG_ImplDX11_CreateDeviceObjects())return;
    if(!g_VB||g_VBSize<data->total_vtx){if(g_VB)g_VB->Release();g_VBSize=data->total_vtx+5000;D3D11_BUFFER_DESC d={};d.Usage=D3D11_USAGE_DYNAMIC;d.ByteWidth=(UINT)(g_VBSize*sizeof(og::DrawVert));d.BindFlags=D3D11_BIND_VERTEX_BUFFER;d.CPUAccessFlags=D3D11_CPU_ACCESS_WRITE;if(FAILED(g_Device->CreateBuffer(&d,0,&g_VB)))return;}if(!g_IB||g_IBSize<data->total_idx){if(g_IB)g_IB->Release();g_IBSize=data->total_idx+10000;D3D11_BUFFER_DESC d={};d.Usage=D3D11_USAGE_DYNAMIC;d.ByteWidth=(UINT)(g_IBSize*sizeof(og::DrawIdx));d.BindFlags=D3D11_BIND_INDEX_BUFFER;d.CPUAccessFlags=D3D11_CPU_ACCESS_WRITE;if(FAILED(g_Device->CreateBuffer(&d,0,&g_IB)))return;}
    D3D11_MAPPED_SUBRESOURCE vm={},im={};if(FAILED(g_Context->Map(g_VB,0,D3D11_MAP_WRITE_DISCARD,0,&vm))||FAILED(g_Context->Map(g_IB,0,D3D11_MAP_WRITE_DISCARD,0,&im)))return;og::DrawVert* vd=(og::DrawVert*)vm.pData;og::DrawIdx* id=(og::DrawIdx*)im.pData;for(size_t n=0;n<data->lists.size();++n){og::DrawList* dl=data->lists[n];memcpy(vd,dl->vtx.data(),dl->vtx.size()*sizeof(*vd));memcpy(id,dl->idx.data(),dl->idx.size()*sizeof(*id));vd+=dl->vtx.size();id+=dl->idx.size();}g_Context->Unmap(g_VB,0);g_Context->Unmap(g_IB,0);
    D3D11_MAPPED_SUBRESOURCE mapped={};if(SUCCEEDED(g_Context->Map(g_ConstantBuffer,0,D3D11_MAP_WRITE_DISCARD,0,&mapped))){float L=data->display_pos.x,R=L+data->display_size.x,T=data->display_pos.y,B=T+data->display_size.y;float m[4][4]={{2/(R-L),0,0,0},{0,2/(T-B),0,0},{0,0,0.5f,0},{(R+L)/(L-R),(T+B)/(B-T),0.5f,1}};memcpy(mapped.pData,m,sizeof(m));g_Context->Unmap(g_ConstantBuffer,0);}
    D3D11_VIEWPORT vp={0,0,data->display_size.x*og::GetIO().framebuffer_scale.x,data->display_size.y*og::GetIO().framebuffer_scale.y,0,1};g_Context->RSSetViewports(1,&vp);UINT stride=sizeof(og::DrawVert),offset=0;g_Context->IASetInputLayout(g_Layout);g_Context->IASetVertexBuffers(0,1,&g_VB,&stride,&offset);g_Context->IASetIndexBuffer(g_IB,DXGI_FORMAT_R32_UINT,0);g_Context->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);g_Context->VSSetShader(g_VS,0,0);g_Context->VSSetConstantBuffers(0,1,&g_ConstantBuffer);g_Context->PSSetShader(g_PS,0,0);g_Context->PSSetSamplers(0,1,&g_Sampler);const float blend[4]={0,0,0,0};g_Context->OMSetBlendState(g_Blend,blend,0xffffffff);g_Context->OMSetDepthStencilState(g_Depth,0);g_Context->RSSetState(g_Raster);
    int global_v=0,global_i=0;for(size_t n=0;n<data->lists.size();++n){og::DrawList* dl=data->lists[n];for(size_t c=0;c<dl->cmds.size();++c){const og::DrawCmd& cmd=dl->cmds[c];if(!cmd.elem_count)continue;D3D11_RECT r={(LONG)cmd.clip_rect.x,(LONG)cmd.clip_rect.y,(LONG)cmd.clip_rect.z,(LONG)cmd.clip_rect.w};g_Context->RSSetScissorRects(1,&r);ID3D11ShaderResourceView* texture=FindTexture(cmd.tex_id);g_Context->PSSetShaderResources(0,1,&texture);g_Context->DrawIndexed(cmd.elem_count,cmd.idx_offset+global_i,global_v);}global_i+=(int)dl->idx.size();global_v+=(int)dl->vtx.size();}
}
