# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 4.3

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\mrwge\Documents\anti gravity\claude\osgui\cmake\package-consumer"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\mrwge\Documents\anti gravity\claude\osgui\consumer-verify-buildtree"

# Include any dependencies generated for this target.
include CMakeFiles\osgui_package_consumer.dir\depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles\osgui_package_consumer.dir\compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles\osgui_package_consumer.dir\progress.make

# Include the compile flags for this target's objects.
include CMakeFiles\osgui_package_consumer.dir\flags.make

CMakeFiles\osgui_package_consumer.dir\codegen:
.PHONY : CMakeFiles\osgui_package_consumer.dir\codegen

CMakeFiles\osgui_package_consumer.dir\main.cpp.obj: CMakeFiles\osgui_package_consumer.dir\flags.make
CMakeFiles\osgui_package_consumer.dir\main.cpp.obj: "C:\Users\mrwge\Documents\anti gravity\claude\osgui\cmake\package-consumer\main.cpp"
CMakeFiles\osgui_package_consumer.dir\main.cpp.obj: CMakeFiles\osgui_package_consumer.dir\compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir="C:\Users\mrwge\Documents\anti gravity\claude\osgui\consumer-verify-buildtree\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/osgui_package_consumer.dir/main.cpp.obj"
	$(CMAKE_COMMAND) -E cmake_cl_compile_depends --dep-file=CMakeFiles\osgui_package_consumer.dir\main.cpp.obj.d --working-dir="C:\Users\mrwge\Documents\anti gravity\claude\osgui\consumer-verify-buildtree" --filter-prefix="Note: including file: " -- C:\PROGRA~1\MICROS~2\18\COMMUN~1\VC\Tools\MSVC\1451~1.362\bin\Hostx64\x64\cl.exe @<<
 /nologo /TP $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) /showIncludes /FoCMakeFiles\osgui_package_consumer.dir\main.cpp.obj /FdCMakeFiles\osgui_package_consumer.dir\ /FS -c "C:\Users\mrwge\Documents\anti gravity\claude\osgui\cmake\package-consumer\main.cpp"
<<

CMakeFiles\osgui_package_consumer.dir\main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/osgui_package_consumer.dir/main.cpp.i"
	C:\PROGRA~1\MICROS~2\18\COMMUN~1\VC\Tools\MSVC\1451~1.362\bin\Hostx64\x64\cl.exe > CMakeFiles\osgui_package_consumer.dir\main.cpp.i @<<
 /nologo /TP $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\mrwge\Documents\anti gravity\claude\osgui\cmake\package-consumer\main.cpp"
<<

CMakeFiles\osgui_package_consumer.dir\main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/osgui_package_consumer.dir/main.cpp.s"
	C:\PROGRA~1\MICROS~2\18\COMMUN~1\VC\Tools\MSVC\1451~1.362\bin\Hostx64\x64\cl.exe @<<
 /nologo /TP $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) /FoNUL /FAs /FaCMakeFiles\osgui_package_consumer.dir\main.cpp.s /c "C:\Users\mrwge\Documents\anti gravity\claude\osgui\cmake\package-consumer\main.cpp"
<<

# Object files for target osgui_package_consumer
osgui_package_consumer_OBJECTS = \
"CMakeFiles\osgui_package_consumer.dir\main.cpp.obj"

# External object files for target osgui_package_consumer
osgui_package_consumer_EXTERNAL_OBJECTS =

osgui_package_consumer.exe: CMakeFiles\osgui_package_consumer.dir\main.cpp.obj
osgui_package_consumer.exe: CMakeFiles\osgui_package_consumer.dir\build.make
osgui_package_consumer.exe: "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build-verify-release\osgui.lib"
osgui_package_consumer.exe: "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build-verify-release\osgui_examples.lib"
osgui_package_consumer.exe: "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build-verify-release\osgui_opengl3.lib"
osgui_package_consumer.exe: "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build-verify-release\osgui_win32_opengl2.lib"
osgui_package_consumer.exe: "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build-verify-release\osgui_dx11.lib"
osgui_package_consumer.exe: "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build-verify-release\osgui.lib"
osgui_package_consumer.exe: CMakeFiles\osgui_package_consumer.dir\objects1.rsp
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --bold --progress-dir="C:\Users\mrwge\Documents\anti gravity\claude\osgui\consumer-verify-buildtree\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_2) "Linking CXX executable osgui_package_consumer.exe"
	"C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --msvc-ver=1951 --intdir=CMakeFiles\osgui_package_consumer.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100261~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100261~1.0\x64\mt.exe --manifests -- C:\PROGRA~1\MICROS~2\18\COMMUN~1\VC\Tools\MSVC\1451~1.362\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\osgui_package_consumer.dir\objects1.rsp @<<
 /out:osgui_package_consumer.exe /implib:osgui_package_consumer.lib /pdb:"C:\Users\mrwge\Documents\anti gravity\claude\osgui\consumer-verify-buildtree\osgui_package_consumer.pdb" /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console  "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build-verify-release\osgui.lib" "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build-verify-release\osgui_examples.lib" "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build-verify-release\osgui_opengl3.lib" "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build-verify-release\osgui_win32_opengl2.lib" "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build-verify-release\osgui_dx11.lib" opengl32.lib gdi32.lib user32.lib "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build-verify-release\osgui.lib" d3d11.lib d3dcompiler.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  
<<

# Rule to build all files generated by this target.
CMakeFiles\osgui_package_consumer.dir\build: osgui_package_consumer.exe
.PHONY : CMakeFiles\osgui_package_consumer.dir\build

CMakeFiles\osgui_package_consumer.dir\clean:
	$(CMAKE_COMMAND) -P CMakeFiles\osgui_package_consumer.dir\cmake_clean.cmake
.PHONY : CMakeFiles\osgui_package_consumer.dir\clean

CMakeFiles\osgui_package_consumer.dir\depend:
	$(CMAKE_COMMAND) -E cmake_depends "NMake Makefiles" "C:\Users\mrwge\Documents\anti gravity\claude\osgui\cmake\package-consumer" "C:\Users\mrwge\Documents\anti gravity\claude\osgui\cmake\package-consumer" "C:\Users\mrwge\Documents\anti gravity\claude\osgui\consumer-verify-buildtree" "C:\Users\mrwge\Documents\anti gravity\claude\osgui\consumer-verify-buildtree" "C:\Users\mrwge\Documents\anti gravity\claude\osgui\consumer-verify-buildtree\CMakeFiles\osgui_package_consumer.dir\DependInfo.cmake" "--color=$(COLOR)" osgui_package_consumer
.PHONY : CMakeFiles\osgui_package_consumer.dir\depend

