# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 4.3

# compile CXX with C:/Program Files/Microsoft Visual Studio/18/Community/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/cl.exe
CXX_DEFINES = 

CXX_INCLUDES = -external:I"C:\Users\mrwge\Documents\anti gravity\claude\osgui\build-verify-debug\install\include\osgui" -external:W0

CXX_FLAGS = /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -MDd

