#include "osgui.h"
#include "osgui_examples.h"
#include <math.h>

namespace og {
void ShowSettingsExample(bool* open){SetNextWindowSize(Vec2(620,560));if(!Begin("Example / Settings",open)){End();return;}static bool autosave=true,telemetry=false;static int language=0;static float volume=0.7f;static char profile[64]="Developer";Text("Application settings");Separator();InputText("Profile",profile,64);const char* languages[]={"English","Deutsch","Japanese","Spanish"};Combo("Language",&language,languages,4);Checkbox("Automatic saves",&autosave);Checkbox("Anonymous telemetry",&telemetry);SliderFloat("Notification volume",&volume,0,1,"%.0f%%");if(Button("Save settings"))AddToast("Settings saved",Toast_Success);End();}
void ShowLauncherExample(bool* open){SetNextWindowSize(Vec2(700,470));if(!Begin("Example / Launcher",open)){End();return;}static int channel=0;static bool verify=true;TextColored(Vec4(.55f,.93f,.85f,1),"OSGUI LAUNCHER");TextDisabled("Version 0.5 / renderer-ready workspace");GlassCard("All systems operational",Vec2(-1,64),7);const char* channels[]={"Stable","Preview","Nightly"};Combo("Release channel",&channel,channels,3);Checkbox("Verify assets before launch",&verify);ProgressBar(.82f,Vec2(-1,30),"Preparing shaders");if(Button("Launch workspace",Vec2(180,38)))AddToast("Workspace launched",Toast_Success);End();}
void ShowFileBrowserExample(bool* open){SetNextWindowSize(Vec2(720,520));if(!Begin("Example / File Browser",open)){End();return;}static char filter[96]="";static int selected=0;InputText("Filter",filter,96);TextDisabled("C:/Projects/osgui");if(BeginTable("files",3,TableFlags_Borders|TableFlags_RowBg|TableFlags_Sortable)){TableHeader("Name");TableHeader("Type");TableHeader("Size");const char* names[]={"examples","osgui.cpp","osgui.h","README.md"};const char* types[]={"Folder","C++ source","C++ header","Markdown"};const char* sizes[]={"--","86 KB","18 KB","14 KB"};for(int i=0;i<4;++i){if(TableSelectable(names[i],selected==i))selected=i;TableSelectable(types[i]);TableSelectable(sizes[i]);}EndTable();}Text("Selected: %s",selected==0?"examples":selected==1?"osgui.cpp":selected==2?"osgui.h":"README.md");End();}
void ShowPerformanceMonitorExample(bool* open){SetNextWindowSize(Vec2(760,540));if(!Begin("Example / Performance Monitor",open)){End();return;}static StreamingSeries cpu(240),gpu(240);static float t=0;t+=GetIO().delta_time;cpu.Push(42+sinf(t*2.1f)*18);gpu.Push(58+sinf(t*1.4f+1)*14);Text("Live performance");SameLine();TextDisabled("%.0f FPS",GetIO().framerate);if(BeginChart("CPU and GPU / percent",Vec2(-1,210))){ChartLine("CPU",cpu);ChartLine("GPU",gpu,GetColorU32(Col_Warning));EndChart();}Candlestick candles[]={Candlestick(32,48,28,43),Candlestick(43,51,39,41),Candlestick(41,56,40,53),Candlestick(53,57,45,47),Candlestick(47,61,46,59)};if(BeginChart("Frame ranges",Vec2(-1,180))){ChartCandlesticks("Frame",candles,5);EndChart();}End();}
}
