# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 4.3

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\mrwge\Documents\anti gravity\claude\osgui"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build"

# Include any dependencies generated for this target.
include CMakeFiles\osgui_dx11.dir\depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles\osgui_dx11.dir\compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles\osgui_dx11.dir\progress.make

# Include the compile flags for this target's objects.
include CMakeFiles\osgui_dx11.dir\flags.make

CMakeFiles\osgui_dx11.dir\codegen:
.PHONY : CMakeFiles\osgui_dx11.dir\codegen

CMakeFiles\osgui_dx11.dir\osgui_impl_dx11.cpp.obj: CMakeFiles\osgui_dx11.dir\flags.make
CMakeFiles\osgui_dx11.dir\osgui_impl_dx11.cpp.obj: "C:\Users\mrwge\Documents\anti gravity\claude\osgui\osgui_impl_dx11.cpp"
CMakeFiles\osgui_dx11.dir\osgui_impl_dx11.cpp.obj: CMakeFiles\osgui_dx11.dir\compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir="C:\Users\mrwge\Documents\anti gravity\claude\osgui\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/osgui_dx11.dir/osgui_impl_dx11.cpp.obj"
	$(CMAKE_COMMAND) -E cmake_cl_compile_depends --dep-file=CMakeFiles\osgui_dx11.dir\osgui_impl_dx11.cpp.obj.d --working-dir="C:\Users\mrwge\Documents\anti gravity\claude\osgui\build" --filter-prefix="Note: including file: " -- C:\PROGRA~1\MICROS~2\18\COMMUN~1\VC\Tools\MSVC\1451~1.362\bin\Hostx64\x64\cl.exe @<<
 /nologo /TP $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) /showIncludes /FoCMakeFiles\osgui_dx11.dir\osgui_impl_dx11.cpp.obj /FdCMakeFiles\osgui_dx11.dir\osgui_dx11.pdb /FS -c "C:\Users\mrwge\Documents\anti gravity\claude\osgui\osgui_impl_dx11.cpp"
<<

CMakeFiles\osgui_dx11.dir\osgui_impl_dx11.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/osgui_dx11.dir/osgui_impl_dx11.cpp.i"
	C:\PROGRA~1\MICROS~2\18\COMMUN~1\VC\Tools\MSVC\1451~1.362\bin\Hostx64\x64\cl.exe > CMakeFiles\osgui_dx11.dir\osgui_impl_dx11.cpp.i @<<
 /nologo /TP $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\mrwge\Documents\anti gravity\claude\osgui\osgui_impl_dx11.cpp"
<<

CMakeFiles\osgui_dx11.dir\osgui_impl_dx11.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/osgui_dx11.dir/osgui_impl_dx11.cpp.s"
	C:\PROGRA~1\MICROS~2\18\COMMUN~1\VC\Tools\MSVC\1451~1.362\bin\Hostx64\x64\cl.exe @<<
 /nologo /TP $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) /FoNUL /FAs /FaCMakeFiles\osgui_dx11.dir\osgui_impl_dx11.cpp.s /c "C:\Users\mrwge\Documents\anti gravity\claude\osgui\osgui_impl_dx11.cpp"
<<

# Object files for target osgui_dx11
osgui_dx11_OBJECTS = \
"CMakeFiles\osgui_dx11.dir\osgui_impl_dx11.cpp.obj"

# External object files for target osgui_dx11
osgui_dx11_EXTERNAL_OBJECTS =

osgui_dx11.lib: CMakeFiles\osgui_dx11.dir\osgui_impl_dx11.cpp.obj
osgui_dx11.lib: CMakeFiles\osgui_dx11.dir\build.make
osgui_dx11.lib: CMakeFiles\osgui_dx11.dir\objects1.rsp
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --bold --progress-dir="C:\Users\mrwge\Documents\anti gravity\claude\osgui\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_2) "Linking CXX static library osgui_dx11.lib"
	$(CMAKE_COMMAND) -P CMakeFiles\osgui_dx11.dir\cmake_clean_target.cmake
	C:\PROGRA~1\MICROS~2\18\COMMUN~1\VC\Tools\MSVC\1451~1.362\bin\Hostx64\x64\lib.exe /nologo /machine:x64 /out:osgui_dx11.lib @CMakeFiles\osgui_dx11.dir\objects1.rsp

# Rule to build all files generated by this target.
CMakeFiles\osgui_dx11.dir\build: osgui_dx11.lib
.PHONY : CMakeFiles\osgui_dx11.dir\build

CMakeFiles\osgui_dx11.dir\clean:
	$(CMAKE_COMMAND) -P CMakeFiles\osgui_dx11.dir\cmake_clean.cmake
.PHONY : CMakeFiles\osgui_dx11.dir\clean

CMakeFiles\osgui_dx11.dir\depend:
	$(CMAKE_COMMAND) -E cmake_depends "NMake Makefiles" "C:\Users\mrwge\Documents\anti gravity\claude\osgui" "C:\Users\mrwge\Documents\anti gravity\claude\osgui" "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build" "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build" "C:\Users\mrwge\Documents\anti gravity\claude\osgui\build\CMakeFiles\osgui_dx11.dir\DependInfo.cmake" "--color=$(COLOR)" osgui_dx11
.PHONY : CMakeFiles\osgui_dx11.dir\depend

